name: Workflow 3
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run:
    runs-on: windows-latest

    steps:
        - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    
      - name: Pull Docker image
        run: docker pull task1repo/sampleimg

      - name: Run container and display text file
        run: |
          docker run --rm task1repo/sampleimg cat sample.txt
