name: Workflow 3
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run:
    runs-on: windows-latest

    steps:
      - name: Pull Docker image
        run: docker pull your-docker-registry/your-image-name:latest

      - name: Run container and display text file
        run: |
          docker run --rm your-docker-registry/your-image-name:latest type sample.txt
