name: Workflow 2
on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Read text file
        id: read-file
        run: echo "::set-output name=file_content::$(cat prem.txt)"

      - name: Create Dockerfile
        id: create-dockerfile
        run: |
          echo "${{ steps.read-file.outputs.file_content }}" > Dockerfile
          echo "ADD . /app" >> Dockerfile

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        id: build-image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: task1repo/your-docker-image-name:latest

 
