name: Workflow 1
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Append to file
        run: |
          file_path="prem.txt"
          echo "This line will be appended to the file." | tee -a "$file_path"


   
 
