name: Workflow 1
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Git
        run: |
          git config --global user.email "kpremkumar28120@gmail.com"
          git config --global user.name "premkumar2812"

      - name: Create sample text file
        run: cat <<EOF > sample.txt
             this is prem kumar from Genesys Chennai
             EOF
      - name: Commit and push changes
        env:
            TOKEN: ${{ secrets.PAT }}
        run: |
              git add sample.txt
              git commit -m "Add sample text file"

