name: Triggering Workflow
on:
  push:
    paths:
      - "prem.txt"

 

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest

 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

