name: Workflow 1
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Append to file
        run: |
          echo "This line will be appended to the file." | tee -a "prem.txt"
          cat "prem.txt"
      - name: Display the contents
        run: |
           cat "prem.txt"
      - name: Debug
        run: ls
          



   
 
