name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read file content
      id: read-file
      run: echo "::set-output name=file_content::$(cat file.txt)"

    - name: Create Dockerfile
      run: |
        echo "FROM ubuntu:latest" > Dockerfile
        echo "RUN echo '${{ steps.read-file.outputs.file_content }}' > app.txt" >> Dockerfile
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with: 
           context: .
           push: true
           tags: your-docker-repo:latest
      env:
            DOCKER_AUTH_CONFIG: '{"auths":{"https://index.docker.io/v1/":{"auth":"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"}}}'
