name: Workflow 1

on:
  workflow_dispatch:
    inputs:
      content:
        description: 'Content to add'
        required: true

jobs:
  add-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create content file
        run: echo "hello" > content.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "premkumar2812"
          git config --global user.email "kpremkumar28120@gmail.com"
          git add content.txt
          git commit -m "Add content file"
          git push
         
 
