name: Triggering Workflow
on:
  push:
    paths:
      - "prem.txt"

 

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest

 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Trigger Workflow 1
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          repository: premkumar2812/task1
          event-type: trigger-workflow-1
