name: Workflow 1

on:
  workflow_dispatch:

jobs:
  add_content:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Create file
        run: |
          echo "Sample text content" > file.txt
        
      - name: Commit changes
        run: |
          git config --global user.email kpremkumar28120@gmail.com
          git config --global user.name premkumar2812
          git config --global --add safe.directory /github/workspace
          git add file.txt
          git commit -m "Add sample text content"
        
      - name: Push changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
