name: Monitor Changes

on:
  push:
    paths:
      - 'prem.txt'

jobs:
  check_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      # Add any additional steps you may need here to run checks or tests based on the changes.

      - name: Trigger Another Workflow
        uses: actions/workflow-dispatch@v2
        with:
          workflow: workflow1.yml
          # You can pass any input parameters to the triggered workflow, if needed.
          # Example: input1: "value1", input2: "value2"
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
