name: Add Content

on:
  workflow_dispatch:

jobs:
  add-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create content file
        run: echo "This is a sample text content." > content.txt

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add content file
          file_pattern: content.txt
