name: Trigger On Text File Changes

on:
  push:
    paths:
      - 'prem.txt'

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Existing Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          workflow: 'Workflow 1'
          ref: ${{ github.sha }}
