name: Scheduled Workflow

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  run_container:
    name: Run Docker Container and Cat Text File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker Image
        run: docker pull premkumar2812/task1:newtag

      - name: Run Docker Container
        run: docker run docker pull premkumar2812/task1:newtag  cat "prem.txt"
