name: Workflow 1
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create sample text file
        run: echo this is prem kumar from Genesys chennai > sample.txt

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Add sample text file"
          git push
