name: Workflow 2

 

on:
  repository_dispatch:
    types: [trigger-workflow-2]

 

jobs:
  build:
    runs-on: ubuntu-latest

 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to docker hub
        uses: docker/login-action@v1

        with:
           username: ${{  secrets.DOCKER_USERNAME  }}
           password: ${{  secrets.DOCKER_PASSWORD  }}
      - name: Build Docker image
        run: |
          docker build -t my-docker-image .
          docker run -d my-docker-image
      - name: List images
        run: |
         docker image ls
         realpath my-docker-image
      #- name: Tag image
        #run: |
         #docker tag my-docker-image:latest indhu1024/workflow 


      - name: Push Docker image to Docker Hub
        run: |
           docker tag my-docker-image:latest indhu1024/workflow:newtag
           docker image push indhu1024/workflow:newtag/my-docker-image:latest

       # run: docker image push my-docker-image:latest
#docker tag my-docker-image:latest your-username/your-repo:newtag

 

#docker tag <local image name> <hub username/image name>

 

#docker image push <hub username/image name>
