name: Monitor Changes

on:
  push:
    paths:
      - 'prem.txt'

jobs:
  check_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      # Add any additional steps you may need here to run checks or tests based on the changes.

      - name: Trigger Another Workflow
        uses: actions/github-script@v5
        with:
          script: |
            const token = process.env.WORKFLOW_TOKEN;
            const octokit = new Octokit({ auth: token });
            octokit.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'workflow1.yml',
            });
