name: Trigger Workflow on Text File Changes

on:
  push:
    paths:
      - 'prem.txt'

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trigger Existing Workflow
        run: |
          # Replace 'existing-workflow-name' with the name of your existing workflow.
          # You can find it in the "name" field of the existing workflow file.
          # Make sure to use the correct file paths as per your repository structure.
          # The following line triggers the existing workflow
          curl -X POST -H "Authorization: Bearer ${{ secrets.WORKFLOW_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/Workflow 1/dispatches \
          -d '{"ref":"${{ github.sha }}"}'
